print(x)

##Error appears that:NameError: name 'x' is not defined 